# Generated by Django 5.2.7 on 2025-10-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_rating', models.FloatField(help_text='Power rating in watts')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_used', models.FloatField(help_text='Number of hours used')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appliance')),
            ],
        ),
    ]
