# Generated by Django 4.2 on 2026-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_appliance_threshold_hours_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Requires digital meter monitoring'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Monitoring priority'),
        ),
    ]
