# Generated by Django 4.2 on 2026-01-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alert_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.appliance'),
        ),
    ]
