# Generated by Django 4.2 on 2026-01-12 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_alter_alert_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default profile for alerts'),
        ),
        migrations.AddField(
            model_name='resident',
            name='profile_name',
            field=models.CharField(default=1, help_text="Name for this profile (e.g., 'Main Household', 'Vacation Home')", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resident',
            unique_together={('user', 'profile_name')},
        ),
    ]
