# Generated by Django 4.2 on 2026-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_resident_is_default_resident_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
