# Generated by Django 4.2 on 2026-01-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alert_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='email_password',
            field=models.CharField(blank=True, help_text='Email account password (for sending alerts)', max_length=100),
        ),
    ]
