# Generated by Django 6.0.1 on 2026-02-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_resident_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='dashboard.resident'),
        ),
    ]
