# Generated by Django 6.0.1 on 2026-02-01 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_appliance_resident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyApplianceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_hours', models.FloatField(default=0.0)),
                ('total_energy_kwh', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('avg_daily_hours', models.FloatField(default=0.0)),
                ('threshold_exceeded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appliance')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.resident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'year', 'month'], name='dashboard_m_user_id_23e687_idx'), models.Index(fields=['appliance', 'year', 'month'], name='dashboard_m_applian_5fede8_idx')],
                'unique_together': {('appliance', 'year', 'month')},
            },
        ),
    ]
