# Generated by Django 4.2 on 2026-03-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_monthlyapplianceusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_method', models.CharField(blank=True, choices=[('DASHBOARD', 'Dashboard'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='monthlyapplianceusage',
            name='dashboard_m_user_id_23e687_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyapplianceusage',
            name='dashboard_m_applian_5fede8_idx',
        ),
        migrations.RemoveField(
            model_name='monthlyapplianceusage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlyapplianceusage',
            name='notes',
        ),
        migrations.AddField(
            model_name='alert',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email_password',
            field=models.CharField(blank=True, help_text='App password for sending alerts', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='profile_name',
            field=models.CharField(help_text="Name for this profile (e.g., 'Main Household')", max_length=100),
        ),
        migrations.AddField(
            model_name='alertconfirmation',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='dashboard.alert'),
        ),
    ]
