"""
Django settings for household_electricity_dashboard project.

Generated by Django 4.0.0
"""

import os
from pathlib import Path

# --------------------------------------------------
# Base Directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Security
# --------------------------------------------------
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7xk9$9@mauritius-electricity-dashboard-2025')

DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',')

# Security settings for production
if not DEBUG:
    # Only enable HTTPS security settings in production
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    # Development mode: disable HTTPS redirects to allow HTTP development server
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Always enable these security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# --------------------------------------------------
# Installed Applications
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'dashboard',
]

# --------------------------------------------------
# Middleware
# --------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------
# URLs & WSGI
# --------------------------------------------------
ROOT_URLCONF = 'household_electricity_dashboard.urls'

WSGI_APPLICATION = 'household_electricity_dashboard.wsgi.application'

# --------------------------------------------------
# Templates
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Make sure dashboard/context_processors.py exists
                'dashboard.context_processors.unread_alerts_count',
            ],
        },
    },
]

# --------------------------------------------------
# Database (SQLite – acceptable for coursework)
# --------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Monitoring System',
        'USER': 'root',
        'PASSWORD': 'vik1258',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    },
}

# --------------------------------------------------
# Password Validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------
# Internationalization (Mauritius)
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Indian/Mauritius'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# --------------------------------------------------
# Static Files
# --------------------------------------------------
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'dashboard' / 'static',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------
# Authentication
# --------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# --------------------------------------------------
# Email Configuration (Safe placeholders) - update with production credentials
# --------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Temporary: if set to True the SMTP client will not validate server TLS certificates.
# Useful for local networks or when a local proxy re-signs certificates. **Do not enable in production.**
EMAIL_TRUST_ALL_CERTS = True

EMAIL_HOST_USER = 'starkytony19@gmail.com'  # your project Gmail account
EMAIL_HOST_PASSWORD = '2499 1868'  # app-specific password for Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# NOTE: Appliance mirroring code was removed from settings.py because runtime logic
# should not live in settings. See `dashboard/models.py` for a safe post_save signal
# that mirrors newly created or updated `Appliance` rows into the `mysql` database
# (if configured).

# Celery dev convenience: when DEBUG=True run tasks eagerly (synchronously)
# so background work can run without a broker during development.
CELERY_TASK_ALWAYS_EAGER = DEBUG

# Celery broker/backend (override in environment for production)
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)

# --------------------------------------------------
# Tuya IoT Cloud (Smart Plug Live Monitoring)
# --------------------------------------------------
# Uses environment variables first, then falls back to the provided project values.
TUYA_ACCESS_ID = os.getenv('TUYA_ACCESS_ID', 'hajwhyq3qxpvqpgywsjv')
TUYA_ACCESS_SECRET = os.getenv('TUYA_ACCESS_SECRET', '74daf71999c048b29a7183b67ed5a6f1')
# Central Europe Data Center endpoint (use global EU hostname for cloud projects)
TUYA_BASE_URL = os.getenv('TUYA_BASE_URL', 'https://openapi.tuyaeu.com')
# IMPORTANT: Use Tuya Cloud "Device ID" (not product/model id)
TUYA_DEVICE_ID = os.getenv('TUYA_DEVICE_ID', 'bffc3502fd940182f8mdoe')

# --------------------------------------------------
# Twilio WhatsApp Alerts
# --------------------------------------------------
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')
# Example: whatsapp:+14155238886 (Twilio sandbox) or your approved WA sender
TWILIO_WHATSAPP_FROM = os.getenv('TWILIO_WHATSAPP_FROM', '')

# --------------------------------------------------
# Twilio SMS Alerts
# --------------------------------------------------
TWILIO_SMS_ENABLED = os.getenv('TWILIO_SMS_ENABLED', 'False').lower() == 'true'
TWILIO_SMS_THRESHOLD_KWH = float(os.getenv('TWILIO_SMS_THRESHOLD_KWH', '5.0'))
TWILIO_SMS_THRESHOLD_HOURS = float(os.getenv('TWILIO_SMS_THRESHOLD_HOURS', '2.0'))

# --------------------------------------------------
# Mauritius Electricity Tariffs (editable slabs)
# Format: (upper_kwh_limit, rate_mur_per_kwh)
# --------------------------------------------------
MAURITIUS_TARIFF_BLOCKS = [
    (50, 3.50),
    (100, 5.00),
    (200, 6.50),
    (float('inf'), 8.00),
]

